#include "home.h"

/* home_page.html embedded as C string.
   Source of truth for editing: firmware/main/home_page.html */
static const char home_html[] =
"<!DOCTYPE html>\n"
"<html lang='da'>\n"
"<head>\n"
"<meta charset='UTF-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"<title>Modbus API Gateway</title>\n"
"<style>\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{font-family:system-ui,sans-serif;background:#f0f2f5;color:#222;font-size:14px}\n"
"header{background:#1a2035;color:#fff;padding:12px 20px;display:flex;justify-content:space-between;align-items:center}\n"
"header h1{font-size:15px;font-weight:600;letter-spacing:.3px}\n"
"#hdr-info{font-size:12px;opacity:.65}\n"
"nav{background:#fff;border-bottom:2px solid #e0e4ea;display:flex;padding:0 16px;gap:4px}\n"
"nav a{border:none;background:none;padding:11px 18px;cursor:pointer;font-size:13px;color:#666;border-bottom:3px solid transparent;margin-bottom:-2px;font-weight:500;text-decoration:none;display:inline-block}\n"
"nav a.active{color:#2563eb;border-bottom-color:#2563eb}\n"
"nav a:hover:not(.active){color:#222}\n"
"main{padding:20px;max-width:900px;margin:0 auto}\n"
".hero{background:linear-gradient(135deg,#1a2035,#2b3350);color:#fff;border-radius:10px;padding:34px 30px;margin-bottom:20px;box-shadow:0 2px 8px rgba(0,0,0,.15)}\n"
".hero .ico{font-size:38px;margin-bottom:8px;display:block}\n"
".hero h2{font-size:24px;font-weight:700;margin-bottom:6px}\n"
".hero p{font-size:14px;opacity:.8;max-width:560px;line-height:1.5}\n"
".hero .badges{margin-top:16px;display:flex;gap:10px;flex-wrap:wrap}\n"
".hb{background:rgba(255,255,255,.12);border-radius:99px;padding:5px 14px;font-size:12px;font-weight:600}\n"
".hb.live{background:rgba(16,185,129,.2);color:#6ee7b7}\n"
".hb.live::before{content:'\\25cf';margin-right:6px;font-size:9px}\n"
".card{background:#fff;border-radius:8px;padding:16px 20px;margin-bottom:14px;box-shadow:0 1px 3px rgba(0,0,0,.08)}\n"
".ct{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:#888;margin-bottom:10px}\n"
"table.info{width:100%;border-collapse:collapse}\n"
"table.info td{padding:6px 0;border-bottom:1px solid #f3f4f6;vertical-align:top}\n"
"table.info td:first-child{color:#666;width:150px;font-size:13px}\n"
"table.info td:last-child{font-weight:500}\n"
"table.info tr:last-child td{border-bottom:none}\n"
".grid4{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px;margin-bottom:20px}\n"
".nc{background:#fff;border-radius:8px;padding:20px;box-shadow:0 1px 3px rgba(0,0,0,.08);text-decoration:none;color:#222;display:block;border-top:3px solid #2563eb;transition:transform .15s,box-shadow .15s}\n"
".nc:hover{transform:translateY(-2px);box-shadow:0 4px 12px rgba(0,0,0,.12)}\n"
".nc .ico{font-size:26px;margin-bottom:10px;display:block}\n"
".nc h3{font-size:14px;font-weight:700;margin-bottom:6px}\n"
".nc p{font-size:12.5px;color:#666;line-height:1.5}\n"
".badge{display:inline-block;padding:2px 9px;border-radius:99px;font-size:11px;font-weight:700}\n"
".ok{background:#d1fae5;color:#065f46}.warn{background:#fef3c7;color:#92400e}.err{background:#fee2e2;color:#991b1b}\n"
"footer{text-align:center;padding:24px 0 10px;color:#9ca3af;font-size:12px}\n"
"footer a{color:#6b7280}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <h1>&#9649; Modbus API Gateway</h1>\n"
"  <span id='hdr-info'>indl&#230;ser...</span>\n"
"</header>\n"
"<nav>\n"
"  <a class='active' href='/'>Forside</a>\n"
"  <a href='/mgmt'>Management</a>\n"
"  <a href='/manual'>Manual</a>\n"
"  <a href='/api'>REST API</a>\n"
"  <a href='https://github.com/Jangreenlarsen/Modbus-API-Gateway' target='_blank' rel='noopener'>GitHub &#8599;</a>\n"
"</nav>\n"
"<main>\n"
"\n"
"  <div class='hero'>\n"
"    <span class='ico'>&#128268;</span>\n"
"    <h2>Modbus RTU &#8596; REST API Gateway</h2>\n"
"    <p>Bro mellem Modbus RTU (RS485/RS232) og HTTP REST over Ethernet/WiFi &mdash; hele Modbus-bussen tilg&aelig;ngelig som et almindeligt REST API, ingen specialsoftware n&oslash;dvendig p&aring; klientsiden.</p>\n"
"    <div class='badges'>\n"
"      <span class='hb live' id='b-status'>henter status&hellip;</span>\n"
"      <span class='hb' id='b-ver'>v&hellip;</span>\n"
"      <span class='hb' id='b-ifc'>&hellip; interfaces</span>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <div class='card'>\n"
"    <div class='ct'>System</div>\n"
"    <table class='info' id='sys-table'>\n"
"      <tr><td colspan='2' style='color:#aaa'>Indl&aelig;ser&hellip;</td></tr>\n"
"    </table>\n"
"  </div>\n"
"\n"
"  <div class='grid4'>\n"
"    <a class='nc' href='/mgmt'>\n"
"      <span class='ico'>&#128295;</span>\n"
"      <h3>Management GUI</h3>\n"
"      <p>Konfigur&eacute;r interfaces, overv&aring;g cache og Modbus-log, styr OTA-opdateringer.</p>\n"
"    </a>\n"
"    <a class='nc' href='/manual'>\n"
"      <span class='ico'>&#128214;</span>\n"
"      <h3>Manual</h3>\n"
"      <p>Installation, GPIO pin-tildeling for RS485/RS232, og komplet REST API-guide.</p>\n"
"    </a>\n"
"    <a class='nc' href='/api' target='_blank'>\n"
"      <span class='ico'>&#128279;</span>\n"
"      <h3>REST API-indeks</h3>\n"
"      <p>Selvdokumenterende JSON-liste over alle tilg&aelig;ngelige endpoints p&aring; denne enhed.</p>\n"
"    </a>\n"
"    <a class='nc' href='https://github.com/Jangreenlarsen/Modbus-API-Gateway' target='_blank' rel='noopener'>\n"
"      <span class='ico'>&#128187;</span>\n"
"      <h3>GitHub</h3>\n"
"      <p>Kildekode, releases og changelog for firmwaren.</p>\n"
"    </a>\n"
"  </div>\n"
"\n"
"  <footer id='foot'>Modbus API Gateway</footer>\n"
"</main>\n"
"<script>\n"
"function $(id){return document.getElementById(id);}\n"
"fetch('/api/v1/system').then(function(r){return r.json();}).then(function(s){\n"
"  $('hdr-info').textContent='v'+s.version+' \xe2\x80\xa2 '+(s.ip||'?');\n"
"  $('b-status').textContent='Online';\n"
"  $('b-ver').textContent='v'+s.version+' build '+(s.build||'?');\n"
"  var h=Math.floor(s.uptime_s/3600),m=Math.floor((s.uptime_s%3600)/60);\n"
"  var rows=[\n"
"    ['Version','v'+s.version+' build '+(s.build||'?')],\n"
"    ['IP (Ethernet)',s.ip||'&mdash;'],\n"
"    ['Uptime',h+'t '+m+'m'],\n"
"    ['Fri heap',Math.round(s.free_heap/1024)+' KB'],\n"
"    ['ESP32 board',s.board_variant==='38pin'?'38-pin':'30-pin']\n"
"  ];\n"
"  $('sys-table').innerHTML=rows.map(function(r){return '<tr><td>'+r[0]+'</td><td>'+r[1]+'</td></tr>';}).join('');\n"
"  $('foot').innerHTML='Modbus API Gateway v'+s.version+' build '+(s.build||'?')+' &mdash; <a href=\"https://github.com/Jangreenlarsen/Modbus-API-Gateway\" target=\"_blank\" rel=\"noopener\">GitHub</a>';\n"
"}).catch(function(){\n"
"  $('b-status').textContent='Ingen forbindelse';\n"
"  $('b-status').className='hb';\n"
"  $('sys-table').innerHTML='<tr><td colspan=\"2\" style=\"color:#dc2626\">Kunne ikke hente systemstatus</td></tr>';\n"
"});\n"
"fetch('/api/v1/interfaces').then(function(r){return r.json();}).then(function(ifc){\n"
"  var active=ifc.filter(function(f){return f.enabled;}).length;\n"
"  $('b-ifc').textContent=active+' / '+ifc.length+' interfaces aktive';\n"
"}).catch(function(){});\n"
"</script>\n"
"</body>\n"
"</html>\n";

static esp_err_t get_home_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
    httpd_resp_send(req, home_html, sizeof(home_html) - 1);
    return ESP_OK;
}

const httpd_uri_t route_get_home = {
    .uri     = "/",
    .method  = HTTP_GET,
    .handler = get_home_handler,
};
