#include "manual.h"

/* manual_page.html embedded as C string.
   Source of truth for editing: firmware/main/manual_page.html */
static const char manual_html[] =
"<!DOCTYPE html>\n"
"<html lang='da'>\n"
"<head>\n"
"<meta charset='UTF-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"<title>Modbus API Gateway &mdash; Manual</title>\n"
"<style>\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{font-family:system-ui,sans-serif;background:#f0f2f5;color:#222;font-size:14px;line-height:1.55}\n"
"header{background:#1a2035;color:#fff;padding:12px 20px;display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;z-index:10}\n"
"header h1{font-size:15px;font-weight:600;letter-spacing:.3px}\n"
"#hdr-info{font-size:12px;opacity:.65}\n"
"nav{background:#fff;border-bottom:2px solid #e0e4ea;display:flex;padding:0 16px;gap:4px;position:sticky;top:41px;z-index:10}\n"
"nav a{border:none;background:none;padding:11px 18px;cursor:pointer;font-size:13px;color:#666;border-bottom:3px solid transparent;margin-bottom:-2px;font-weight:500;text-decoration:none;display:inline-block}\n"
"nav a.active{color:#2563eb;border-bottom-color:#2563eb}\n"
"nav a:hover:not(.active){color:#222}\n"
"main{padding:20px;max-width:920px;margin:0 auto}\n"
"h2{font-size:19px;font-weight:700;margin:0 0 14px;padding-bottom:8px;border-bottom:2px solid #e5e7eb;color:#1a2035}\n"
"h3{font-size:15px;font-weight:700;margin:18px 0 8px;color:#1a2035}\n"
"h3:first-child{margin-top:0}\n"
"p{margin:0 0 10px}\n"
".card{background:#fff;border-radius:8px;padding:20px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,.08)}\n"
".card > *:last-child{margin-bottom:0}\n"
".lead{font-size:14px;color:#555;margin-bottom:6px}\n"
".toc{background:#fff;border-radius:8px;padding:18px 24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,.08)}\n"
".toc .ct{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:#888;margin-bottom:10px}\n"
".toc ol{list-style:none;columns:2;column-gap:24px}\n"
".toc li{margin-bottom:6px;break-inside:avoid}\n"
".toc a{color:#2563eb;text-decoration:none;font-size:13px}\n"
".toc a:hover{text-decoration:underline}\n"
".toc .sub{padding-left:14px;font-size:12px}\n"
".toc .sub a{color:#555}\n"
"table.dt{width:100%;border-collapse:collapse;margin:10px 0 16px;font-size:13px}\n"
"table.dt th{background:#f3f4f6;text-align:left;padding:7px 10px;font-weight:700;color:#374151;border-bottom:2px solid #e5e7eb}\n"
"table.dt td{padding:7px 10px;border-bottom:1px solid #f3f4f6;vertical-align:top}\n"
"table.dt tr:last-child td{border-bottom:none}\n"
"table.dt code{background:#eef1f6;padding:1px 5px;border-radius:3px;font-size:12px}\n"
"pre{background:#1a2035;color:#d6deeb;padding:14px 16px;border-radius:6px;overflow-x:auto;font-family:'SFMono-Regular',Consolas,monospace;font-size:12.5px;margin:10px 0 16px;line-height:1.5}\n"
"pre.diagram{background:#0f1420;color:#8fa3c0}\n"
"code{font-family:'SFMono-Regular',Consolas,monospace;background:#eef1f6;padding:1px 5px;border-radius:3px;font-size:12.5px;color:#1e3a8a}\n"
"pre code{background:none;padding:0;color:inherit}\n"
".note{background:#fffbeb;border-left:4px solid #f59e0b;padding:10px 14px;border-radius:0 6px 6px 0;margin:10px 0 16px;font-size:13px}\n"
".note b{color:#92400e}\n"
".warn{background:#fef2f2;border-left:4px solid #ef4444;padding:10px 14px;border-radius:0 6px 6px 0;margin:10px 0 16px;font-size:13px}\n"
".warn b{color:#991b1b}\n"
".tip{background:#eff6ff;border-left:4px solid #2563eb;padding:10px 14px;border-radius:0 6px 6px 0;margin:10px 0 16px;font-size:13px}\n"
".tip b{color:#1e40af}\n"
".top{position:fixed;bottom:20px;right:20px;background:#1a2035;color:#fff;width:38px;height:38px;border-radius:50%;display:flex;align-items:center;justify-content:center;text-decoration:none;font-size:16px;box-shadow:0 2px 8px rgba(0,0,0,.25);opacity:.85}\n"
".top:hover{opacity:1}\n"
"footer{text-align:center;padding:24px 0 10px;color:#9ca3af;font-size:12px}\n"
"ul.plain{margin:0 0 14px 18px}\n"
"ul.plain li{margin-bottom:4px}\n"
"@media(max-width:640px){.toc ol{columns:1}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <h1>&#9649; Modbus API Gateway</h1>\n"
"  <span id='hdr-info'>Manual</span>\n"
"</header>\n"
"<nav>\n"
"  <a href='/'>Forside</a>\n"
"  <a href='/mgmt'>Management</a>\n"
"  <a class='active' href='/manual'>Manual</a>\n"
"  <a href='/api'>REST API</a>\n"
"  <a href='https://github.com/Jangreenlarsen/Modbus-API-Gateway' target='_blank' rel='noopener'>GitHub &#8599;</a>\n"
"</nav>\n"
"<main>\n"
"\n"
"<div class='card' style='background:linear-gradient(135deg,#1a2035,#2b3350);color:#fff'>\n"
"  <h2 style='border:none;color:#fff;margin-bottom:6px'>Komplet manual</h2>\n"
"  <p class='lead' style='color:#cbd5e1'>Installation, hardware-opsætning (GPIO pin-tildeling for RS485/RS232) og en komplet REST API-programmeringsguide.</p>\n"
"</div>\n"
"\n"
"<div class='toc'>\n"
"  <div class='ct'>Indhold</div>\n"
"  <ol>\n"
"    <li><a href='#intro'>1. Introduktion</a></li>\n"
"    <li><a href='#install'>2. Installation &amp; Hardware</a>\n"
"      <ol class='sub'>\n"
"        <li><a href='#krav'>2.1 Hvad du skal bruge</a></li>\n"
"        <li><a href='#gpio-regler'>2.2 GPIO &mdash; grundregler</a></li>\n"
"        <li><a href='#gpio-rs485'>2.3 Pin-tildeling &mdash; RS485</a></li>\n"
"        <li><a href='#gpio-rs232'>2.4 Pin-tildeling &mdash; RS232</a></li>\n"
"        <li><a href='#wiring-485'>2.5 Wiring &mdash; RS485 (MAX485)</a></li>\n"
"        <li><a href='#wiring-232'>2.6 Wiring &mdash; RS232 (MAX232)</a></li>\n"
"        <li><a href='#eth'>2.7 Ethernet-tilslutning</a></li>\n"
"        <li><a href='#hwlimit'>2.8 Begrænsning: HW-UART master/slave</a></li>\n"
"        <li><a href='#firstboot'>2.9 Første opstart</a></li>\n"
"        <li><a href='#netsetup'>2.10 Netværksopsætning</a></li>\n"
"        <li><a href='#ifcsetup'>2.11 Opsætning af et interface</a></li>\n"
"      </ol>\n"
"    </li>\n"
"    <li><a href='#gui'>3. Web Management GUI</a></li>\n"
"    <li><a href='#api'>4. REST API Programmeringsguide</a>\n"
"      <ol class='sub'>\n"
"        <li><a href='#api-basics'>4.1 Grundlæggende</a></li>\n"
"        <li><a href='#api-auth'>4.2 Autentificering</a></li>\n"
"        <li><a href='#api-err'>4.3 Fejl-format</a></li>\n"
"        <li><a href='#api-system'>4.4 System &amp; netværk</a></li>\n"
"        <li><a href='#api-ifc'>4.5 Interface-administration</a></li>\n"
"        <li><a href='#api-fc'>4.6 Function codes FC01&ndash;FC10</a></li>\n"
"        <li><a href='#api-selftest'>4.7 Loopback-selvtest</a></li>\n"
"        <li><a href='#api-cache'>4.8 Register-cache</a></li>\n"
"        <li><a href='#api-mblog'>4.9 Modbus-log</a></li>\n"
"        <li><a href='#api-log'>4.10 API-kald-log</a></li>\n"
"        <li><a href='#api-ota'>4.11 OTA-opdatering</a></li>\n"
"        <li><a href='#api-ws'>4.12 WebSocket</a></li>\n"
"        <li><a href='#api-examples'>4.13 Programmeringseksempler</a></li>\n"
"      </ol>\n"
"    </li>\n"
"    <li><a href='#cli'>5. CLI &mdash; kort reference</a></li>\n"
"    <li><a href='#trouble'>6. Fejlfinding</a></li>\n"
"    <li><a href='#appendix'>7. Appendix</a></li>\n"
"  </ol>\n"
"</div>\n"
"\n"
"<section class='card' id='intro'>\n"
"  <h2>1. Introduktion</h2>\n"
"  <p>Modbus API Gateway er en ESP32-baseret bro mellem <b>Modbus RTU</b> (RS485/RS232, seriel) og <b>REST/HTTP</b> (Ethernet/WiFi). Enheden fungerer som Modbus RTU master (og valgfrit slave) på op til 8 seriel-interfaces samtidig, og eksponerer nøjagtig de samme operationer som standard Modbus function codes via et REST API &mdash; ingen specialsoftware nødvendig på klientsiden.</p>\n"
"  <h3>Kernefunktioner</h3>\n"
"  <ul class='plain'>\n"
"    <li>Fuld FC01&ndash;FC10 REST-mapping (læs/skriv coils, discrete inputs, holding/input registers)</li>\n"
"    <li>Op til 8 seriel-interfaces (2&times; hardware-UART + op til 6&times; software-UART bit-bang)</li>\n"
"    <li>Lokal register-cache med baggrunds-refresh (reducerer bus-trafik og latency)</li>\n"
"    <li>Web-GUI til konfiguration, status, cache-monitorering og dekodet Modbus-log</li>\n"
"    <li>Serial CLI (IOS-stil) til konfiguration uden netværk</li>\n"
"    <li>OTA-opdatering af både firmware og frontend fra GitHub Releases</li>\n"
"    <li>Interface loopback-selvtest til hurtig hardware-diagnose</li>\n"
"  </ul>\n"
"  <p><b>Arkitektur (kort):</b> Frontend &rarr; REST API-lag &rarr; Service-lag &rarr; Modbus-lag &rarr; UART/hardware.</p>\n"
"</section>\n"
"\n"
"<section class='card' id='install'>\n"
"  <h2>2. Installation &amp; Hardware-opsætning</h2>\n"
"\n"
"  <h3 id='krav'>2.1 Hvad du skal bruge</h3>\n"
"  <table class='dt'>\n"
"    <tr><th>Komponent</th><th>Detaljer</th></tr>\n"
"    <tr><td>ESP32-udviklingsboard</td><td>30-pin (standard, fx NodeMCU-32S) eller 38-pin (bred variant, eksponerer GPIO 37+38)</td></tr>\n"
"    <tr><td>Ethernet</td><td><b>W5500</b> (SPI-modul, standard) eller <b>LAN8720</b> (RMII, kræver ESP32 med indbygget EMAC)</td></tr>\n"
"    <tr><td>RS485-transceiver</td><td>MAX485 / SN65HVD3082 pr. RS485-interface</td></tr>\n"
"    <tr><td>RS232-transceiver</td><td>MAX232 / SP3232 pr. RS232-interface</td></tr>\n"
"    <tr><td>Strømforsyning</td><td>5V/USB til ESP32-board; separat 3.3V/5V til transceivere efter datablad</td></tr>\n"
"    <tr><td>USB-til-seriel</td><td>Til første konfiguration via CLI (medmindre boardet har indbygget USB)</td></tr>\n"
"  </table>\n"
"  <p>Board-variant vælges i konfigurationen (<code>PUT /api/v1/system/hardware</code> eller web-GUI) &mdash; det styrer GPIO-preset-værdier og pin-tilgængelighed.</p>\n"
"\n"
"  <h3 id='gpio-regler'>2.2 GPIO &mdash; grundregler og reserverede pins</h3>\n"
"  <table class='dt'>\n"
"    <tr><th>Pins</th><th>Status</th><th>Grund</th></tr>\n"
"    <tr><td>GPIO 6&ndash;11</td><td><b>Aldrig brugbare</b></td><td>Forbundet til intern SPI-flash</td></tr>\n"
"    <tr><td>GPIO 1, 3</td><td>Reserveret (UART0)</td><td>Serial CLI-konsol &mdash; undgå medmindre du opgiver CLI</td></tr>\n"
"    <tr><td>GPIO 34&ndash;39</td><td><b>Kun input</b> (RX)</td><td>Ingen intern pull-up/pull-down, kan ikke bruges som TX eller DE</td></tr>\n"
"    <tr><td>GPIO 0, 2, 5, 12, 15</td><td>Forsigtighed (strapping)</td><td>Påvirker boot-mode &mdash; undgå som DE hvis muligt</td></tr>\n"
"    <tr><td>GPIO 20, 24, 28&ndash;31</td><td>Findes ikke</td><td>Ikke til stede på ESP32</td></tr>\n"
"    <tr><td>GPIO 37, 38</td><td>Kun på 38-pin boards</td><td>Ikke eksponeret på standard 30-pin boards</td></tr>\n"
"  </table>\n"
"  <p>Ethernet optager også pins automatisk:</p>\n"
"  <table class='dt'>\n"
"    <tr><th>Hardware</th><th>Reserverede GPIO (default)</th></tr>\n"
"    <tr><td>W5500 (SPI)</td><td>CS=23, MOSI=13, MISO=12, SCLK=14, RST=33, INT=34</td></tr>\n"
"    <tr><td>LAN8720 (RMII, faste pins)</td><td>0 (CLK), 19 (TXD0), 21 (TX_EN), 22 (TXD1), 25 (RXD0), 26 (RXD1), 27 (CRS_DV) + konfigurerbar MDC/MDIO/PHY-RST</td></tr>\n"
"  </table>\n"
"  <div class='tip'><b>Tip:</b> <code>GET /api/v1/system/gpio</code> returnerer live hvilke GPIO'er der reelt er ledige på din enhed lige nu &mdash; inklusive Ethernet-pins. Samme oversigt vises farvekodet i web-GUI'ens &raquo;RS485 Config&laquo;-fane.</div>\n"
"\n"
"  <h3 id='gpio-rs485'>2.3 Pin-tildeling &mdash; RS485</h3>\n"
"  <p>RS485 er half-duplex og kræver <b>tre</b> GPIO'er pr. interface: TX, RX og <b>DE</b> (Driver Enable). Nedenstående er fabriks-standardpresets (frit ændrbare) &mdash; \"GPIO Preset\"-knappen i GUI'en udfylder dem automatisk.</p>\n"
"  <p><b>30-pin board:</b></p>\n"
"  <table class='dt'>\n"
"    <tr><th>Iface</th><th>TX</th><th>RX</th><th>DE</th><th>Bemærkning</th></tr>\n"
"    <tr><td>0</td><td>17</td><td>16</td><td>4</td><td>HW-UART1 (standard master-port)</td></tr>\n"
"    <tr><td>1</td><td>25</td><td>26</td><td>27</td><td></td></tr>\n"
"    <tr><td>2</td><td>21</td><td>22</td><td>19</td><td></td></tr>\n"
"    <tr><td>3</td><td>32</td><td>35</td><td>15</td><td>RX=35 er input-only (OK til RX)</td></tr>\n"
"    <tr><td>4</td><td>5</td><td>36</td><td>18</td><td>RX=36 er input-only (OK til RX)</td></tr>\n"
"    <tr><td>5</td><td>2</td><td>39</td><td>0</td><td>RX=39 input-only; <b>DE=0 er boot-strap-pin</b> &mdash; brug med forsigtighed</td></tr>\n"
"    <tr><td>6</td><td>15</td><td>34</td><td>4</td><td>RX=34 input-only; <b>DE=4 deler pin med iface 0</b> &mdash; skift ved konflikt</td></tr>\n"
"    <tr><td>7</td><td>18</td><td>38</td><td>19</td><td>GPIO38 kun på visse 30-pin boards &mdash; brug 39 som alternativ</td></tr>\n"
"  </table>\n"
"  <p><b>38-pin board:</b></p>\n"
"  <table class='dt'>\n"
"    <tr><th>Iface</th><th>TX</th><th>RX</th><th>DE</th><th>Bemærkning</th></tr>\n"
"    <tr><td>0</td><td>17</td><td>16</td><td>4</td><td>HW-UART1</td></tr>\n"
"    <tr><td>1</td><td>25</td><td>26</td><td>27</td><td></td></tr>\n"
"    <tr><td>2</td><td>21</td><td>22</td><td>19</td><td></td></tr>\n"
"    <tr><td>3</td><td>32</td><td>35</td><td>15</td><td></td></tr>\n"
"    <tr><td>4</td><td>5</td><td>36</td><td>18</td><td></td></tr>\n"
"    <tr><td>5</td><td>2</td><td>37</td><td>0</td><td>GPIO37 eksponeret på 38-pin boards; DE=0 boot-strap-pin</td></tr>\n"
"    <tr><td>6</td><td>15</td><td>38</td><td>4</td><td>GPIO38 eksponeret på 38-pin boards</td></tr>\n"
"    <tr><td>7</td><td>18</td><td>39</td><td>19</td><td></td></tr>\n"
"  </table>\n"
"  <div class='warn'><b>Vigtigt:</b> Kun interface-id 0 og 1 kan konfigureres som hardware-UART (UART1/UART2, op til 115200 baud). Interface-id 2&ndash;7 er software-UART (bit-bang, maks. 9600 baud) &mdash; se afsnit 2.8.</div>\n"
"\n"
"  <h3 id='gpio-rs232'>2.4 Pin-tildeling &mdash; RS232</h3>\n"
"  <p>RS232 er full-duplex og kræver kun <b>TX + RX</b> &mdash; ingen DE/RE-styring (sæt DE til <code>-1</code>). Brug samme TX/RX som RS485-tabellerne ovenfor.</p>\n"
"  <table class='dt'>\n"
"    <tr><th>Iface</th><th>TX</th><th>RX</th></tr>\n"
"    <tr><td>0</td><td>17</td><td>16</td></tr>\n"
"    <tr><td>1</td><td>25</td><td>26</td></tr>\n"
"    <tr><td>2</td><td>21</td><td>22</td></tr>\n"
"    <tr><td>3</td><td>32</td><td>35</td></tr>\n"
"    <tr><td>4</td><td>5</td><td>36</td></tr>\n"
"    <tr><td>5</td><td>2</td><td>39 (30-pin) / 37 (38-pin)</td></tr>\n"
"    <tr><td>6</td><td>15</td><td>34 (30-pin) / 38 (38-pin)</td></tr>\n"
"    <tr><td>7</td><td>18</td><td>38 (30-pin) / 39 (38-pin)</td></tr>\n"
"  </table>\n"
"  <p>Sæt interface-type til <code>RS232</code> via CLI (<code>type rs232</code>) eller GUI &mdash; DE-feltet skjules/ignoreres automatisk.</p>\n"
"\n"
"  <h3 id='wiring-485'>2.5 Wiring &mdash; RS485-transceiver (MAX485)</h3>\n"
"  <pre class='diagram'>ESP32 GPIO          MAX485 / SN65HVD3082        RS485-bus\n"
"&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;          &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;        &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;\n"
"TX_PIN  &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; DI  (Data In)\n"
"RX_PIN  &#9668;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472; RO  (Receive Out)\n"
"DE_PIN  &#9472;&#9472;&#9472;&#9472;&#9472;&#9484;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; DE  (Driver Enable)\n"
"              &#9492;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; RE&#772;  (Receiver Enable, aktiv lav &mdash; tie med DE)\n"
"                       A  &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; Bus A (+)\n"
"                       B  &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; Bus B (&minus;)\n"
"3.3/5V  &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; VCC  (efter transceiver-datablad)\n"
"GND     &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; GND</pre>\n"
"  <ul class='plain'>\n"
"    <li><b>DE og RE&#772; tied sammen</b> til samme ESP32-GPIO &mdash; firmwaren sætter GPIO højt ved TX og lavt ved RX.</li>\n"
"    <li><b>Terminering:</b> 120&#8486; modstand i <b>begge</b> ender af bus-segmentet ved lange kabler/flere slaver.</li>\n"
"    <li><b>Op til 247 slaves</b> pr. bus-segment (standard Modbus-adresserum 1&ndash;247).</li>\n"
"  </ul>\n"
"\n"
"  <h3 id='wiring-232'>2.6 Wiring &mdash; RS232-transceiver (MAX232)</h3>\n"
"  <pre class='diagram'>ESP32 GPIO          MAX232 / SP3232              RS232 D-SUB9 (DTE)\n"
"&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;          &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;             &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;\n"
"TX_PIN  &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; T1IN &#8594; T1OUT &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; Pin 3 (TXD)\n"
"RX_PIN  &#9668;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472; R1OUT &#8592; R1IN &#9668;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472; Pin 2 (RXD)\n"
"                                                     Pin 5 (GND)\n"
"3.3/5V  &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; VCC (MAX232 kræver typisk 5V + ladningspumpe-kondensatorer)\n"
"GND     &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9658; GND</pre>\n"
"  <ul class='plain'>\n"
"    <li>RS232 er <b>punkt-til-punkt</b> (1:1) &mdash; ingen bus-topologi, ingen terminering, ingen DE-styring.</li>\n"
"    <li>Maks. kabellængde ~15 m ved fuld hastighed.</li>\n"
"    <li>Kryds TX/RX korrekt afhængig af DTE/DCE (nul-modem vs. lige kabel).</li>\n"
"  </ul>\n"
"\n"
"  <h3 id='eth'>2.7 Ethernet-tilslutning</h3>\n"
"  <p><b>W5500 (SPI) &mdash; standard-konfiguration:</b></p>\n"
"  <table class='dt'>\n"
"    <tr><th>ESP32 GPIO</th><th>W5500-pin</th><th>Konfigurérbar via</th></tr>\n"
"    <tr><td>23</td><td>CS</td><td><code>eth cs &lt;gpio&gt;</code></td></tr>\n"
"    <tr><td>13</td><td>MOSI</td><td><code>eth mosi &lt;gpio&gt;</code></td></tr>\n"
"    <tr><td>12</td><td>MISO</td><td><code>eth miso &lt;gpio&gt;</code></td></tr>\n"
"    <tr><td>14</td><td>SCLK</td><td><code>eth sclk &lt;gpio&gt;</code></td></tr>\n"
"    <tr><td>33</td><td>RST</td><td><code>eth rst &lt;gpio|-1&gt;</code></td></tr>\n"
"    <tr><td>34</td><td>INT</td><td><code>eth int &lt;gpio|-1&gt;</code> (se advarsel)</td></tr>\n"
"  </table>\n"
"  <div class='warn'><b>Vigtigt &mdash; INT-pin (GPIO34):</b> GPIO 34&ndash;39 har ingen intern pull-up. Ved interrupt-mode kræves en ekstern <b>pull-up-modstand (4.7&ndash;10 k&#8486; til 3.3V)</b> på INT-pinnen. Uden den kan Ethernet-linket flappe. Alternativt: <code>eth int -1</code> for polling-mode.</div>\n"
"  <p><b>LAN8720 (RMII) &mdash; kræver ESP32 med intern EMAC:</b> Faste pins: GPIO 0 (CLK), 19 (TXD0), 21 (TX_EN), 22 (TXD1), 25 (RXD0), 26 (RXD1), 27 (CRS_DV). MDC/MDIO/PHY-reset er konfigurerbare.</p>\n"
"  <p>Hver enhed får automatisk en <b>unik MAC-adresse</b> udledt af sin egen chip ved boot (logges i seriel-loggen ved Ethernet-init).</p>\n"
"\n"
"  <h3 id='hwlimit'>2.8 Vigtig begrænsning: HW-UART master/slave</h3>\n"
"  <p>Modbus-biblioteket (esp-modbus) bruger en <b>global, delt controller</b> for henholdsvis master- og slave-rollen:</p>\n"
"  <ul class='plain'>\n"
"    <li><b>Højst ét</b> hardware-UART-interface kan være master.</li>\n"
"    <li><b>Højst ét</b> hardware-UART-interface kan være slave.</li>\n"
"    <li>En master og en slave kan sameksistere samtidig (separate globale controllere).</li>\n"
"    <li>Yderligere hardware-interfaces deaktiveres automatisk ved boot med en tydelig log-fejl.</li>\n"
"  </ul>\n"
"  <p>Har du brug for flere end 2 seriel-porte, skal de ekstra interfaces (id 2&ndash;7) konfigureres som <b>software-UART</b> (<code>uart sw</code>) &mdash; maks. 9600 baud.</p>\n"
"\n"
"  <h3 id='firstboot'>2.9 Første opstart</h3>\n"
"  <ol style='margin-left:18px'>\n"
"    <li>Flash firmwaren (PlatformIO/USB, eller senere via OTA).</li>\n"
"    <li>Tilslut USB-seriel til UART0 (TX=GPIO1, RX=GPIO3) hvis boardet mangler indbygget USB.</li>\n"
"    <li>Åbn terminal: 115200 baud, 8N1.</li>\n"
"    <li>Ved boot vises velkomstbanner + <code>gw&gt;</code>-prompt.</li>\n"
"    <li>Skriv <code>help</code> for kommandooversigt.</li>\n"
"  </ol>\n"
"\n"
"  <h3 id='netsetup'>2.10 Netværksopsætning</h3>\n"
"  <p><b>Ethernet (DHCP):</b></p>\n"
"  <pre>gw&gt; eth type w5500\n"
"gw&gt; eth dhcp\n"
"gw&gt; eth enable\n"
"gw&gt; save\n"
"gw&gt; reboot</pre>\n"
"  <p><b>Ethernet (statisk IP):</b></p>\n"
"  <pre>gw&gt; eth 192.168.1.100 192.168.1.1 255.255.255.0\n"
"gw&gt; save\n"
"gw&gt; reboot</pre>\n"
"  <p><b>WiFi:</b></p>\n"
"  <pre>gw&gt; wifi ssid MitNetv&#230;rk\n"
"gw&gt; wifi pass HemmeligKode123\n"
"gw&gt; wifi ip dhcp\n"
"gw&gt; wifi on\n"
"gw&gt; save\n"
"gw&gt; reboot</pre>\n"
"\n"
"  <h3 id='ifcsetup'>2.11 Opsætning af et Modbus-interface</h3>\n"
"  <pre>gw&gt; configure terminal\n"
"gw(config)# interface modbus0\n"
"gw(config-modbus0)# name floor1\n"
"gw(config-modbus0)# mode master\n"
"gw(config-modbus0)# type rs485\n"
"gw(config-modbus0)# uart hw 1\n"
"gw(config-modbus0)# baudrate 19200\n"
"gw(config-modbus0)# format 8 n 1\n"
"gw(config-modbus0)# timeout 500\n"
"gw(config-modbus0)# tx 17\n"
"gw(config-modbus0)# rx 16\n"
"gw(config-modbus0)# de 4\n"
"gw(config-modbus0)# enable\n"
"gw(config-modbus0)# exit\n"
"gw(config)# exit\n"
"gw&gt; save\n"
"gw&gt; reboot</pre>\n"
"  <p>Eller via web-GUI: <a href='/mgmt'>/mgmt</a> &rarr; fanen <b>RS485 Config</b>. Bemærk: ændringer kræver <b>reboot</b> for at træde i kraft (svaret indeholder <code>\"reboot_required\": true</code>).</p>\n"
"  <div class='tip'><b>Tip:</b> Bekræft opsætningen med interface loopback-selvtesten (afsnit 4.7) inden du sætter slaver på bussen.</div>\n"
"</section>\n"
"\n"
"<section class='card' id='gui'>\n"
"  <h2>3. Web Management GUI (/mgmt)</h2>\n"
"  <p>Enheden serverer tre sider direkte fra firmwaren (ingen SPIFFS-afhængighed):</p>\n"
"  <table class='dt'>\n"
"    <tr><th>Side</th><th>URL</th><th>Indhold</th></tr>\n"
"    <tr><td>Forside</td><td><code>/</code></td><td>Live systemstatus + navigationskort til Management/Manual/REST API/GitHub</td></tr>\n"
"    <tr><td>Manual</td><td><code>/manual</code></td><td>Denne manual, tilgængelig direkte på enheden</td></tr>\n"
"    <tr><td>Management GUI</td><td><code>/mgmt</code></td><td>Konfiguration, status og monitorering (se nedenfor)</td></tr>\n"
"  </table>\n"
"  <table class='dt'>\n"
"    <tr><th>Fane</th><th>Indhold</th></tr>\n"
"    <tr><td>Status</td><td>Version, uptime, heap, Ethernet/WiFi-status, interface-oversigt, direkte register-læsning</td></tr>\n"
"    <tr><td>Cache</td><td>Live cache-statistik, hit-rate-graf, entries-tabel, TTL/refresh-indstillinger</td></tr>\n"
"    <tr><td>OTA Opdatering</td><td>Tjek/installér firmware- og frontend-opdateringer fra GitHub Releases</td></tr>\n"
"    <tr><td>RS485 Config</td><td>Interface-CRUD, GPIO-preset, GPIO-tilgængelighedsoversigt, board-variant, loopback-selvtest</td></tr>\n"
"    <tr><td>Modbus Log</td><td>Live dekodet bus-trafik (FC-navn, slave, adresse, status, værdi)</td></tr>\n"
"    <tr><td>API Log</td><td>Live log over alle indkomne HTTP-kald</td></tr>\n"
"  </table>\n"
"</section>\n"
"\n"
"<section class='card' id='api'>\n"
"  <h2>4. REST API Programmeringsguide</h2>\n"
"\n"
"  <h3 id='api-basics'>4.1 Grundlæggende</h3>\n"
"  <ul class='plain'>\n"
"    <li><b>Base URL:</b> <code>http://&lt;enhedens-ip&gt;/api/v1</code></li>\n"
"    <li><b>Format:</b> JSON for alle request-bodies og responses</li>\n"
"    <li><b>Selvdokumenterende:</b> <code>GET /api</code> returnerer en fuld liste over alle endpoints</li>\n"
"    <li><b>Adressering:</b> register/coil-adresser er 0-baserede wire-adresser</li>\n"
"    <li><b>Interface-nøgle (<code>{key}</code>):</b> numerisk id (<code>0</code>, <code>1</code>&hellip;) eller navn-alias (<code>floor1</code>&hellip;) &mdash; case-insensitive</li>\n"
"  </ul>\n"
"\n"
"  <h3 id='api-auth'>4.2 Autentificering</h3>\n"
"  <p>Valgfri API-key-autentificering (<code>auth_enabled</code> + <code>api_key</code> i systemkonfigurationen). Når aktiveret, inkludér:</p>\n"
"  <pre>X-API-Key: &lt;din-n&oslash;gle&gt;</pre>\n"
"  <p>Manglende/forkert nøgle giver <code>401 Unauthorized</code>.</p>\n"
"\n"
"  <h3 id='api-err'>4.3 Fejl-format</h3>\n"
"  <p>Alle Modbus-operationer (FC01&ndash;FC10) bruger et ensartet fejl-format:</p>\n"
"  <table class='dt'>\n"
"    <tr><th>HTTP-status</th><th><code>error</code></th><th>Betydning</th></tr>\n"
"    <tr><td>504</td><td><code>modbus_timeout</code></td><td>Ingen svar fra slave inden for timeout</td></tr>\n"
"    <tr><td>400</td><td><code>modbus_exception</code></td><td>Slave returnerede Modbus-exception (<code>exception_code</code>+<code>description</code>)</td></tr>\n"
"    <tr><td>400</td><td><code>modbus_error</code></td><td>Anden fejl (<code>detail</code>=ESP-IDF-fejlnavn)</td></tr>\n"
"    <tr><td>404</td><td>&mdash;</td><td>Ukendt interface-nøgle eller sti</td></tr>\n"
"    <tr><td>409</td><td>&mdash;</td><td>Fx forsøg på at slette sidste interface</td></tr>\n"
"  </table>\n"
"  <div class='note'><b>Bemærk:</b> <code>exception_code</code> er p.t. kun tilgængelig på software-UART-interfaces. Hardware-UART-fejl rapporteres som <code>modbus_error</code>.</div>\n"
"  <pre>{ \"interface\": 0, \"slave\": 3, \"error\": \"modbus_timeout\", \"description\": \"No response within timeout\" }</pre>\n"
"\n"
"  <h3 id='api-system'>4.4 System &amp; netværk</h3>\n"
"  <table class='dt'>\n"
"    <tr><th>Metode</th><th>Endpoint</th><th>Beskrivelse</th></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/system</code></td><td>Version, build, uptime, IP, heap, board-variant</td></tr>\n"
"    <tr><td>POST</td><td><code>/api/v1/system/reboot</code></td><td>Genstart enheden</td></tr>\n"
"    <tr><td>GET/PUT</td><td><code>/api/v1/system/hardware</code></td><td>Board-variant + GPIO-presets</td></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/system/gpio</code></td><td>GPIO-tilgængelighed (tx/rx/de, reserveret, brugt-af)</td></tr>\n"
"    <tr><td>GET/PUT</td><td><code>/api/v1/system/wifi</code></td><td>WiFi status/konfiguration</td></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/system/wifi/scan</code></td><td>Scan WiFi-netværk</td></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/system/log?since=N</code></td><td>API-kald-log</td></tr>\n"
"    <tr><td>POST</td><td><code>/api/v1/system/log/clear</code></td><td>Ryd API-kald-loggen</td></tr>\n"
"  </table>\n"
"  <pre>GET /api/v1/system\n"
"&#8594;\n"
"{\n"
"  \"version\": \"0.8.1\", \"build\": \"0094\", \"uptime_s\": 3612,\n"
"  \"ip\": \"10.1.32.101\", \"free_heap\": 142336,\n"
"  \"reset_reason\": 1, \"board_variant\": \"30pin\"\n"
"}</pre>\n"
"  <pre>GET /api/v1/system/gpio\n"
"&#8594;\n"
"{\n"
"  \"board_variant\": \"30pin\",\n"
"  \"gpios\": [\n"
"    { \"gpio\": 17, \"tx\": true, \"rx\": true, \"de\": true, \"input_only\": false,\n"
"      \"caution\": false, \"used_by\": 0, \"used_role\": \"TX\" },\n"
"    { \"gpio\": 23, \"tx\": false, \"rx\": false, \"de\": false, \"input_only\": false,\n"
"      \"caution\": false, \"reserved_by\": \"ethernet\" }\n"
"  ]\n"
"}</pre>\n"
"\n"
"  <h3 id='api-ifc'>4.5 Interface-administration</h3>\n"
"  <table class='dt'>\n"
"    <tr><th>Metode</th><th>Endpoint</th><th>Beskrivelse</th></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/interfaces</code></td><td>Liste over alle interfaces</td></tr>\n"
"    <tr><td>POST</td><td><code>/api/v1/interfaces</code></td><td>Opret nyt interface (SW-UART master, defaults)</td></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/interfaces/{key}</code></td><td>Hent ét interfaces konfiguration</td></tr>\n"
"    <tr><td>PUT</td><td><code>/api/v1/interfaces/{key}</code></td><td>Opdatér interface-konfiguration</td></tr>\n"
"    <tr><td>DELETE</td><td><code>/api/v1/interfaces/{key}</code></td><td>Slet interface (renummererer resterende)</td></tr>\n"
"  </table>\n"
"  <pre>{\n"
"  \"id\": 0, \"name\": \"floor1\", \"type\": \"RS485\", \"uart_mode\": \"hw\",\n"
"  \"mode\": \"master\", \"slave_addr\": 1, \"uart\": 1, \"baudrate\": 19200,\n"
"  \"data_bits\": 8, \"parity\": 0, \"stop_bits\": 1, \"timeout_ms\": 500,\n"
"  \"tx_pin\": 17, \"rx_pin\": 16, \"rts_pin\": 4, \"enabled\": true\n"
"}</pre>\n"
"  <p><code>parity</code>: 0=ingen, 1=ulige, 2=lige. <code>rts_pin</code>=DE/RE-pin (sæt -1 for RS232).</p>\n"
"  <div class='note'><b>Bemærk:</b> PUT/POST-svar inkluderer <code>\"reboot_required\": true</code> &mdash; ændringer gemmes straks, men interfaces genindlæses først ved reboot.</div>\n"
"\n"
"  <h3 id='api-fc'>4.6 Modbus function codes (FC01&ndash;FC10)</h3>\n"
"  <p>Alle FC-endpoints: <code>/api/v1/interfaces/{key}/slaves/{sid}/...</code> hvor <code>{sid}</code> er slave-adressen (1&ndash;247).</p>\n"
"\n"
"  <p><b>FC01 &mdash; Read Coils</b> (maks. count: 2000)</p>\n"
"  <pre>GET /api/v1/interfaces/0/slaves/3/coils?start=0&amp;count=8\n"
"&#8594;\n"
"{ \"interface\": 0, \"slave\": 3, \"function\": 1, \"start\": 0, \"count\": 8,\n"
"  \"coils\": [true, false, false, true, false, false, false, false] }</pre>\n"
"\n"
"  <p><b>FC02 &mdash; Read Discrete Inputs</b> (maks. count: 2000)</p>\n"
"  <pre>GET /api/v1/interfaces/0/slaves/3/discrete-inputs?start=0&amp;count=8\n"
"&#8594;\n"
"{ \"interface\": 0, \"slave\": 3, \"function\": 2, \"start\": 0, \"count\": 8,\n"
"  \"inputs\": [true, false, false, false, false, false, false, false] }</pre>\n"
"\n"
"  <p><b>FC03 &mdash; Read Holding Registers</b> (maks. count: 125)</p>\n"
"  <pre>GET /api/v1/interfaces/0/slaves/3/holding-registers?start=100&amp;count=3\n"
"&#8594;\n"
"{ \"interface\": 0, \"slave\": 3, \"function\": 3, \"start\": 100, \"count\": 3,\n"
"  \"registers\": [1234, 5678, 9012] }</pre>\n"
"\n"
"  <p><b>FC04 &mdash; Read Input Registers</b> (maks. count: 125)</p>\n"
"  <pre>GET /api/v1/interfaces/0/slaves/3/input-registers?start=0&amp;count=10\n"
"&#8594;\n"
"{ \"interface\": 0, \"slave\": 3, \"function\": 4, \"start\": 0, \"count\": 10,\n"
"  \"registers\": [301, 302, 303, 0, 0, 0, 0, 0, 0, 0] }</pre>\n"
"\n"
"  <p><b>FC05 &mdash; Write Single Coil</b></p>\n"
"  <pre>PUT /api/v1/interfaces/0/slaves/3/coils/5\n"
"Body: {\"value\": true}\n"
"&#8594;\n"
"{ \"interface\": 0, \"slave\": 3, \"coil\": 5, \"value\": true }</pre>\n"
"\n"
"  <p><b>FC06 &mdash; Write Single Register</b></p>\n"
"  <pre>PUT /api/v1/interfaces/0/slaves/3/holding-registers/100\n"
"Body: {\"value\": 1234}\n"
"&#8594;\n"
"{ \"interface\": 0, \"slave\": 3, \"register\": 100, \"value\": 1234 }</pre>\n"
"\n"
"  <p><b>FC0F (15) &mdash; Write Multiple Coils</b> (maks. 1968 værdier)</p>\n"
"  <pre>PUT /api/v1/interfaces/0/slaves/3/coils?start=0\n"
"Body: {\"values\": [true, false, true, true]}\n"
"&#8594;\n"
"{ \"interface\": 0, \"slave\": 3, \"start\": 0, \"count\": 4 }</pre>\n"
"\n"
"  <p><b>FC10 (16) &mdash; Write Multiple Registers</b> (maks. 123 værdier)</p>\n"
"  <pre>PUT /api/v1/interfaces/0/slaves/3/holding-registers?start=100\n"
"Body: {\"values\": [1234, 5678, 9012]}\n"
"&#8594;\n"
"{ \"interface\": 0, \"slave\": 3, \"start\": 100, \"count\": 3 }</pre>\n"
"  <p>Alle otte endpoints returnerer det <a href='#api-err'>fælles fejl-format</a> ved timeout/exception/fejl.</p>\n"
"\n"
"  <h3 id='api-selftest'>4.7 Interface loopback-selvtest</h3>\n"
"  <p>Verificér TX&rarr;RX-stien på et interface uden slaver tilsluttet.</p>\n"
"  <pre>POST /api/v1/interfaces/{key}/selftest\n"
"Body: {\"mode\": \"internal\"}   // eller \"external\"\n"
"&#8594;\n"
"{\n"
"  \"interface\": 0, \"passed\": true, \"mode\": \"internal\",\n"
"  \"tx_bytes\": 8, \"rx_bytes\": 8, \"mismatches\": 0,\n"
"  \"duration_ms\": 5, \"detail\": \"OK — telegram modtaget retur på RX\"\n"
"}</pre>\n"
"  <ul class='plain'>\n"
"    <li><b>internal</b> &mdash; intern UART-loopback (ingen ledninger). Kun HW-UART master.</li>\n"
"    <li><b>external</b> &mdash; kræver fysisk jumper (TX&harr;RX / A&harr;B). Tester hele stien inkl. transceiver.</li>\n"
"    <li>Software-UART og slave-mode understøttes ikke.</li>\n"
"  </ul>\n"
"\n"
"  <h3 id='api-cache'>4.8 Register-cache</h3>\n"
"  <table class='dt'>\n"
"    <tr><th>Metode</th><th>Endpoint</th><th>Beskrivelse</th></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/cache/stats</code></td><td>Hits, misses, hit-rate, refresh-tællere</td></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/cache/entries</code></td><td>Alle cache-entries</td></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/cache/history</code></td><td>60 tidsserie-samples</td></tr>\n"
"    <tr><td>PUT</td><td><code>/api/v1/cache/config</code></td><td><code>{\"enabled\":true,\"ttl_ms\":1000}</code></td></tr>\n"
"    <tr><td>POST</td><td><code>/api/v1/cache/clear</code></td><td>Tøm cachen</td></tr>\n"
"    <tr><td>POST</td><td><code>/api/v1/cache/reset-stats</code></td><td>Nulstil tællere</td></tr>\n"
"  </table>\n"
"\n"
"  <h3 id='api-mblog'>4.9 Modbus-log (dekodet bus-trafik)</h3>\n"
"  <pre>GET /api/v1/modbus/log?since=N\n"
"&#8594;\n"
"{\n"
"  \"n\": 542,\n"
"  \"entries\": [\n"
"    { \"seq\": 541, \"t\": 88213, \"if\": 0, \"sl\": 3, \"fc\": 3, \"ad\": 100, \"ct\": 3, \"st\": 0, \"v\": 1234 },\n"
"    { \"seq\": 542, \"t\": 88950, \"if\": 0, \"sl\": 5, \"fc\": 6, \"ad\": 10, \"ct\": 1, \"st\": 1 }\n"
"  ]\n"
"}</pre>\n"
"  <p><code>st</code>: 0=OK, 1=timeout, 2=exception, 3=fejl. <code>POST /api/v1/modbus/log/clear</code> rydder loggen.</p>\n"
"\n"
"  <h3 id='api-log'>4.10 API-kald-log</h3>\n"
"  <pre>GET /api/v1/system/log?since=N\n"
"&#8594;\n"
"{ \"n\": 88, \"entries\": [ { \"seq\": 88, \"t\": 88213, \"m\": \"GET\", \"u\": \"/api/v1/system\" } ] }</pre>\n"
"\n"
"  <h3 id='api-ota'>4.11 OTA-opdatering</h3>\n"
"  <table class='dt'>\n"
"    <tr><th>Metode</th><th>Endpoint</th><th>Beskrivelse</th></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/system/ota/check</code></td><td>Tjek GitHub Releases</td></tr>\n"
"    <tr><td>POST</td><td><code>/api/v1/system/ota/firmware</code></td><td>Start firmware-OTA</td></tr>\n"
"    <tr><td>POST</td><td><code>/api/v1/system/ota/frontend</code></td><td>Start frontend-OTA</td></tr>\n"
"    <tr><td>GET</td><td><code>/api/v1/system/ota/status</code></td><td>Poll fremdrift</td></tr>\n"
"  </table>\n"
"  <p><code>POST</code>-kaldene svarer øjeblikkeligt; download/flash sker i baggrunden. Ved succesfuld firmware-OTA genstarter enheden automatisk.</p>\n"
"\n"
"  <h3 id='api-ws'>4.12 WebSocket</h3>\n"
"  <p><code>GET /ws</code> broadcaster automatisk hver ny Modbus-bus-transaktion (læsning/skrivning via REST eller CLI) til alle tilsluttede klienter &mdash; real-time monitorering uden polling.</p>\n"
"  <div class='note'><b>Bemærk:</b> kun transaktioner der rent faktisk rammer bussen udløser en push. Et REST-kald der besvares fra register-cachen (afsnit 4.8) genererer ingen bus-transaktion og derfor ingen WS-hændelse &mdash; samme betydning af &raquo;transaktion&laquo; som i Modbus-loggen (afsnit 4.9).</div>\n"
"  <p><b>Beskedformat</b> &mdash; hver push er &eacute;t enkelt JSON-objekt, samme felter som &eacute;t element i <code>entries</code>-arrayet fra <code>GET /api/v1/modbus/log</code> (afsnit 4.9):</p>\n"
"  <pre>{ \"seq\": 542, \"t\": 88950, \"if\": 0, \"sl\": 5, \"fc\": 6, \"ad\": 10, \"ct\": 1, \"st\": 0, \"v\": 500 }</pre>\n"
"  <p><b>JavaScript-eksempel:</b></p>\n"
"  <pre>const ws = new WebSocket(`ws://${location.host}/ws`);\n"
"ws.onmessage = (ev) => {\n"
"  const e = JSON.parse(ev.data);\n"
"  console.log(`iface${e.if} slave${e.sl} FC${e.fc} @${e.ad} = ${e.v}`);\n"
"};</pre>\n"
"  <p>Polling mod <code>GET /api/v1/modbus/log?since=N</code> virker stadig som f&oslash;r, og er et nyttigt fallback/gap-filler hvis WebSocket-forbindelsen falder ud.</p>\n"
"\n"
"  <h3 id='api-examples'>4.13 Programmeringseksempler</h3>\n"
"  <p><b>curl:</b></p>\n"
"  <pre>curl \"http://10.1.32.101/api/v1/interfaces/floor1/slaves/3/holding-registers?start=0&amp;count=5\"\n"
"\n"
"curl -X PUT http://10.1.32.101/api/v1/interfaces/floor1/slaves/3/holding-registers/10 \\\n"
"  -H \"Content-Type: application/json\" -d '{\"value\": 500}'</pre>\n"
"  <p><b>Python (requests):</b></p>\n"
"  <pre>import requests\n"
"BASE = \"http://10.1.32.101/api/v1\"\n"
"\n"
"def read_holding(iface, slave, start, count):\n"
"    r = requests.get(f\"{BASE}/interfaces/{iface}/slaves/{slave}/holding-registers\",\n"
"                      params={\"start\": start, \"count\": count})\n"
"    r.raise_for_status()\n"
"    return r.json()[\"registers\"]\n"
"\n"
"def write_register(iface, slave, addr, value):\n"
"    r = requests.put(f\"{BASE}/interfaces/{iface}/slaves/{slave}/holding-registers/{addr}\",\n"
"                      json={\"value\": value})\n"
"    r.raise_for_status()\n"
"    return r.json()</pre>\n"
"  <p><b>JavaScript (fetch / Node 18+):</b></p>\n"
"  <pre>const BASE = \"http://10.1.32.101/api/v1\";\n"
"\n"
"async function readCoils(iface, slave, start, count) {\n"
"  const r = await fetch(`${BASE}/interfaces/${iface}/slaves/${slave}/coils?start=${start}&count=${count}`);\n"
"  if (!r.ok) throw new Error((await r.json()).error);\n"
"  return (await r.json()).coils;\n"
"}\n"
"\n"
"async function writeCoil(iface, slave, addr, value) {\n"
"  const r = await fetch(`${BASE}/interfaces/${iface}/slaves/${slave}/coils/${addr}`, {\n"
"    method: \"PUT\",\n"
"    headers: { \"Content-Type\": \"application/json\" },\n"
"    body: JSON.stringify({ value }),\n"
"  });\n"
"  if (!r.ok) throw new Error((await r.json()).error);\n"
"  return r.json();\n"
"}</pre>\n"
"  <div class='tip'><b>Fejlhåndtering (alle sprog):</b> tjek altid HTTP-status. 2xx = succes, ellers parse JSON-body'ens <code>error</code>-felt for at skelne timeout/exception/valideringsfejl.</div>\n"
"</section>\n"
"\n"
"<section class='card' id='cli'>\n"
"  <h2>5. CLI &mdash; kort reference</h2>\n"
"  <table class='dt'>\n"
"    <tr><th>Kommando</th><th>Formål</th></tr>\n"
"    <tr><td><code>help</code></td><td>Vis alle kommandoer</td></tr>\n"
"    <tr><td><code>show config</code></td><td>Vis komplet gemt konfiguration</td></tr>\n"
"    <tr><td><code>status</code></td><td>Live systemstatus</td></tr>\n"
"    <tr><td><code>show ethernet</code> / <code>show wifi</code></td><td>Live netværksstatus</td></tr>\n"
"    <tr><td><code>eth &hellip;</code></td><td>Ethernet-konfiguration</td></tr>\n"
"    <tr><td><code>wifi &hellip;</code></td><td>WiFi-konfiguration</td></tr>\n"
"    <tr><td><code>configure terminal</code> &rarr; <code>interface modbus&lt;N&gt;</code></td><td>Modbus-interface-konfiguration</td></tr>\n"
"    <tr><td><code>save</code></td><td>Gem konfiguration til NVS</td></tr>\n"
"    <tr><td><code>reboot</code></td><td>Genstart</td></tr>\n"
"  </table>\n"
"  <div class='note'><b>Husk altid:</b> &laquo;konfigurér&raquo; &rarr; <code>save</code> &rarr; <code>reboot</code> &mdash; ændringer i RAM er tabt ved genstart uden <code>save</code>.</div>\n"
"</section>\n"
"\n"
"<section class='card' id='trouble'>\n"
"  <h2>6. Fejlfinding</h2>\n"
"  <table class='dt'>\n"
"    <tr><th>Symptom</th><th>Sandsynlig årsag</th><th>Handling</th></tr>\n"
"    <tr><td>Ethernet-link flapper</td><td>Manglende ekstern pull-up på W5500 INT-pin, eller dårlig GND</td><td>Tilføj 4.7&ndash;10 k&#8486; pull-up til 3.3V på INT, eller <code>eth int -1</code></td></tr>\n"
"    <tr><td>Alle enheder samme MAC-adresse</td><td>Rettet i v0.8.1+</td><td>Opdatér firmware</td></tr>\n"
"    <tr><td><code>GPIO_PIN mask error</code> i loggen</td><td>Interface konfigureret med tx/rx = -1</td><td>Tildel gyldige GPIO'er, eller slet interfacet</td></tr>\n"
"    <tr><td>REST-kald rammer forkert interface efter CRUD</td><td>Ændringer kræver reboot</td><td><code>save</code> + <code>reboot</code> efter interface-CRUD</td></tr>\n"
"    <tr><td><code>modbus_timeout</code> ved alle kald</td><td>Forkert baudrate/paritet, DE-pin virker ikke, slave ikke tilsluttet</td><td>Kør loopback-selvtest for at isolere UART fra bus</td></tr>\n"
"    <tr><td>Kun ét af flere HW-interfaces virker</td><td>Forventet begrænsning (afsnit 2.8)</td><td>Brug software-UART til ekstra interfaces</td></tr>\n"
"    <tr><td>OTA \"ingen opdatering\" trods ny release</td><td>Version matcher allerede</td><td>Tjek <code>GET /api/v1/system</code> mod GitHub-tag</td></tr>\n"
"  </table>\n"
"</section>\n"
"\n"
"<section class='card' id='appendix'>\n"
"  <h2>7. Appendix</h2>\n"
"  <h3>7.1 Modbus exception-koder</h3>\n"
"  <table class='dt'>\n"
"    <tr><th>Kode</th><th>Navn</th><th>Betydning</th></tr>\n"
"    <tr><td>1</td><td>Illegal Function</td><td>Function code ikke understøttet af slave</td></tr>\n"
"    <tr><td>2</td><td>Illegal Data Address</td><td>Register/coil-adresse findes ikke</td></tr>\n"
"    <tr><td>3</td><td>Illegal Data Value</td><td>Ugyldig værdi i request</td></tr>\n"
"    <tr><td>4</td><td>Slave Device Failure</td><td>Slave fejlede internt</td></tr>\n"
"    <tr><td>5</td><td>Acknowledge</td><td>Slave accepteret, behandler stadig</td></tr>\n"
"    <tr><td>6</td><td>Slave Device Busy</td><td>Slave optaget &mdash; prøv igen</td></tr>\n"
"    <tr><td>8</td><td>Memory Parity Error</td><td>Parity-fejl i slavens hukommelse</td></tr>\n"
"    <tr><td>10</td><td>Gateway Path Unavailable</td><td>Modbus-gateway-specifik</td></tr>\n"
"    <tr><td>11</td><td>Gateway Target Device Failed To Respond</td><td>Modbus-gateway-specifik</td></tr>\n"
"  </table>\n"
"  <h3>7.2 HTTP-statuskoder</h3>\n"
"  <table class='dt'>\n"
"    <tr><th>Kode</th><th>Betydning</th></tr>\n"
"    <tr><td>200 OK</td><td>Succes</td></tr>\n"
"    <tr><td>201 Created</td><td>Interface oprettet</td></tr>\n"
"    <tr><td>400 Bad Request</td><td>Ugyldig body/parameter, eller Modbus-fejl</td></tr>\n"
"    <tr><td>401 Unauthorized</td><td>Manglende/forkert API-nøgle</td></tr>\n"
"    <tr><td>404 Not Found</td><td>Ukendt interface/route</td></tr>\n"
"    <tr><td>409 Conflict</td><td>Fx sidste interface / max nået</td></tr>\n"
"    <tr><td>502 Bad Gateway</td><td>GitHub utilgængelig (OTA-check)</td></tr>\n"
"    <tr><td>504 Gateway Timeout</td><td>Modbus-slave svarede ikke</td></tr>\n"
"  </table>\n"
"  <h3>7.3 Versionshistorik</h3>\n"
"  <p>Fuld historik: <a href='https://github.com/Jangreenlarsen/Modbus-API-Gateway/blob/main/CHANGELOG.md' target='_blank' rel='noopener'>CHANGELOG.md</a> (teknisk) og <a href='https://github.com/Jangreenlarsen/Modbus-API-Gateway/blob/main/RELEASE_NOTES.md' target='_blank' rel='noopener'>RELEASE_NOTES.md</a> (brugervenligt) på GitHub.</p>\n"
"</section>\n"
"\n"
"<footer>Modbus API Gateway &mdash; <a href='/'>Forside</a> &middot; <a href='/mgmt'>Management</a> &middot; <a href='https://github.com/Jangreenlarsen/Modbus-API-Gateway' target='_blank' rel='noopener'>GitHub</a></footer>\n"
"</main>\n"
"<a class='top' href='#' title='Til toppen'>&#8593;</a>\n"
"</body>\n"
"</html>\n";

static esp_err_t get_manual_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
    httpd_resp_send(req, manual_html, sizeof(manual_html) - 1);
    return ESP_OK;
}

const httpd_uri_t route_get_manual = {
    .uri     = "/manual",
    .method  = HTTP_GET,
    .handler = get_manual_handler,
};
