#include "mgmt.h"

/* mgmt_page.html embedded as C string.
   Source of truth for editing: firmware/main/mgmt_page.html */
static const char mgmt_html[] =
"<!DOCTYPE html>\n"
"<html lang='da'>\n"
"<head>\n"
"<meta charset='UTF-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"<title>Modbus GW \xe2\x80\x94 Mgmt</title>\n"
"<style>\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{font-family:system-ui,sans-serif;background:#f0f2f5;color:#222;font-size:14px}\n"
"header{background:#1a2035;color:#fff;padding:12px 20px;display:flex;justify-content:space-between;align-items:center}\n"
"header h1{font-size:15px;font-weight:600;letter-spacing:.3px}\n"
"#hdr-info{font-size:12px;opacity:.65}\n"
"nav{background:#fff;border-bottom:2px solid #e0e4ea;display:flex;padding:0 16px;gap:4px}\n"
"nav button{border:none;background:none;padding:11px 18px;cursor:pointer;font-size:13px;color:#666;border-bottom:3px solid transparent;margin-bottom:-2px;font-weight:500}\n"
"nav button.active{color:#2563eb;border-bottom-color:#2563eb}\n"
"main{padding:20px;max-width:860px;margin:0 auto}\n"
".page{display:none}.page.active{display:block}\n"
".card{background:#fff;border-radius:8px;padding:16px 20px;margin-bottom:14px;box-shadow:0 1px 3px rgba(0,0,0,.08)}\n"
".ct{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:#888;margin-bottom:10px}\n"
"table.info{width:100%;border-collapse:collapse}\n"
"table.info td{padding:6px 0;border-bottom:1px solid #f3f4f6;vertical-align:top}\n"
"table.info td:first-child{color:#666;width:150px;font-size:13px}\n"
"table.info td:last-child{font-weight:500}\n"
"table.info tr:last-child td{border-bottom:none}\n"
".badge{display:inline-block;padding:2px 9px;border-radius:99px;font-size:11px;font-weight:700}\n"
".ok{background:#d1fae5;color:#065f46}.warn{background:#fef3c7;color:#92400e}.err{background:#fee2e2;color:#991b1b}\n"
".ifc{background:#fff;border-radius:8px;padding:16px 20px;margin-bottom:12px;box-shadow:0 1px 3px rgba(0,0,0,.08);border-left:4px solid #2563eb}\n"
".ifc.off{border-left-color:#d1d5db}\n"
".ifc-hdr{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}\n"
".ifc-name{font-weight:700;font-size:14px}\n"
".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:10px;margin-bottom:14px}\n"
".grid label{display:flex;flex-direction:column;gap:3px;font-size:12px;color:#666;font-weight:500}\n"
".grid select,.grid input{border:1px solid #d1d5db;border-radius:5px;padding:6px 8px;font-size:13px;background:#fff;color:#222}\n"
".row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:6px}\n"
".btn{border:none;padding:8px 16px;border-radius:6px;cursor:pointer;font-size:13px;font-weight:600}\n"
".btn:disabled{opacity:.5;cursor:default}\n"
".btn-p{background:#2563eb;color:#fff}.btn-s{background:#f3f4f6;color:#374151;border:1px solid #d1d5db}.btn-d{background:#ef4444;color:#fff}\n"
".btn-sm{padding:5px 11px;font-size:12px}\n"
".tog{display:flex;align-items:center;gap:8px;cursor:pointer;user-select:none}\n"
".tog input[type=checkbox]{display:none}\n"
".ttrack{width:36px;height:20px;background:#d1d5db;border-radius:99px;position:relative;flex-shrink:0}\n"
".ttrack::after{content:'';position:absolute;top:2px;left:2px;width:16px;height:16px;background:#fff;border-radius:50%;box-shadow:0 1px 2px rgba(0,0,0,.25);transition:left .2s}\n"
".tog input:checked+.ttrack{background:#2563eb}\n"
".tog input:checked+.ttrack::after{left:18px}\n"
".progbar{background:#e5e7eb;border-radius:99px;height:8px;overflow:hidden;margin:10px 0 4px}\n"
".progfill{height:100%;background:#2563eb;border-radius:99px;transition:width .4s}\n"
".progtext{font-size:12px;color:#666}\n"
"#toast{position:fixed;bottom:20px;right:20px;background:#1a2035;color:#fff;padding:10px 18px;border-radius:8px;font-size:13px;opacity:0;transition:opacity .3s;pointer-events:none;z-index:9999}\n"
"#toast.show{opacity:1}#toast.err{background:#dc2626}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <h1>&#9649; Modbus API Gateway &mdash; Management</h1>\n"
"  <span id='hdr-info'>indl&#230;ser...</span>\n"
"</header>\n"
"<nav>\n"
"  <button class='active' id='btn-status'     onclick='tab(\"status\")'>Status</button>\n"
"  <button               id='btn-cache'      onclick='tab(\"cache\")'>Cache</button>\n"
"  <button               id='btn-ota'        onclick='tab(\"ota\")'>OTA Opdatering</button>\n"
"  <button               id='btn-interfaces' onclick='tab(\"interfaces\")'>RS485 Config</button>\n"
"</nav>\n"
"<main>\n"
"\n"
"<div id='p-status' class='page active'>\n"
"  <div class='card'><div class='ct'>System</div><table class='info' id='t-sys'><tr><td colspan='2' style='color:#aaa'>Indl&#230;ser...</td></tr></table></div>\n"
"  <div class='card'><div class='ct'>Netv&#230;rk</div><table class='info' id='t-net'><tr><td colspan='2' style='color:#aaa'>Indl&#230;ser...</td></tr></table></div>\n"
"  <div class='card'><div class='ct'>Modbus Interfaces</div><table class='info' id='t-ifc'><tr><td colspan='2' style='color:#aaa'>Indl&#230;ser...</td></tr></table></div>\n"
"  <div class='row' style='justify-content:flex-end'>\n"
"    <button class='btn btn-s btn-sm' onclick='loadStatus()'>&#8635; Opdater</button>\n"
"    <button class='btn btn-d btn-sm' onclick='doReboot()'>Genstart gateway</button>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div id='p-cache' class='page'>\n"
"  <div class='card'>\n"
"    <div class='ct'>Cache statistik</div>\n"
"    <table class='info' id='t-cache-stats'><tr><td colspan='2' style='color:#aaa'>Indl&aelig;ser...</td></tr></table>\n"
"    <div class='row' style='margin-top:14px;gap:10px;flex-wrap:wrap;align-items:center'>\n"
"      <label class='tog'><input type='checkbox' id='cache-en' onchange='saveCacheCfg()'><div class='ttrack'></div><span style='font-size:13px;color:#666'>Cache aktiv</span></label>\n"
"      <label class='tog'><input type='checkbox' id='cache-rfr' onchange='saveCacheCfg()'><div class='ttrack'></div><span style='font-size:13px;color:#666'>Baggrunds-refresh</span></label>\n"
"      <label style='display:flex;align-items:center;gap:6px;font-size:13px;color:#666'>TTL (ms)<input type='number' id='cache-ttl' style='width:80px;border:1px solid #d1d5db;border-radius:5px;padding:4px 8px' min='0' max='3600000' step='100' onchange='saveCacheCfg()'></label>\n"
"      <button class='btn btn-s btn-sm' onclick='loadCache()'>&#8635; Opdater</button>\n"
"      <button class='btn btn-s btn-sm' onclick='resetCacheStats()'>Nulstil stats</button>\n"
"      <button class='btn btn-d btn-sm' onclick='clearCache()'>T&oslash;m cache</button>\n"
"    </div>\n"
"  </div>\n"
"  <div class='card'>\n"
"    <div class='ct'>Historisk performance</div>\n"
"    <div id='cache-history' style='font-size:12px'>\n"
"      <div style='margin-bottom:8px'><span style='color:#2563eb;font-weight:600'>&#9632;</span> Hit rate &nbsp; <span style='color:#dc2626;font-weight:600'>&#9632;</span> Requests/s &nbsp; <span style='color:#16a34a;font-weight:600'>&#9632;</span> Refreshes/s</div>\n"
"      <svg id='svg-hist' viewBox='0 0 600 180' style='width:100%;height:180px;background:#fafbfc;border:1px solid #e5e7eb;border-radius:4px'></svg>\n"
"      <table class='info' id='t-hist-summary' style='margin-top:10px'></table>\n"
"    </div>\n"
"  </div>\n"
"  <div class='card'>\n"
"    <div class='ct'>Cache-entries (live)</div>\n"
"    <div id='cache-table' style='max-height:520px;overflow:auto;font-size:12px'><p style='color:#aaa;padding:12px'>Indl&aelig;ser...</p></div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div id='p-ota' class='page'>\n"
"  <div class='card'>\n"
"    <div class='ct'>Firmware Opdatering via GitHub</div>\n"
"    <table class='info' id='t-ota'><tr><td colspan='2' style='color:#aaa'>Tryk \"Tjek\" for at s&#248;ge</td></tr></table>\n"
"    <div class='row' style='margin-top:14px'>\n"
"      <button class='btn btn-s' onclick='otaCheck()'>Tjek for opdatering</button>\n"
"      <button class='btn btn-p' id='btn-flash' style='display:none' onclick='otaFlash()'>Installer firmware</button>\n"
"    </div>\n"
"    <div id='ota-prog' style='display:none;margin-top:12px'>\n"
"      <div class='progbar'><div class='progfill' id='ota-fill' style='width:0%'></div></div>\n"
"      <p class='progtext' id='ota-txt'></p>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div id='p-interfaces' class='page'>\n"
"  <div id='ifc-list'><p style='color:#aaa;padding:12px'>Indl&#230;ser...</p></div>\n"
"  <div class='row' style='justify-content:flex-end;margin-top:4px'>\n"
"    <button class='btn btn-s btn-sm' onclick='loadIfc()'>&#8635; Genindl&#230;s</button>\n"
"  </div>\n"
"</div>\n"
"\n"
"</main>\n"
"<div id='toast'></div>\n"
"<script>\n"
"var $=function(id){return document.getElementById(id);};\n"
"function row(k,v){return '<tr><td>'+k+'</td><td>'+v+'</td></tr>';}\n"
"function badge(t,c){return '<span class=\"badge '+c+'\">'+t+'</span>';}\n"
"function toast(msg,err){\n"
"  var el=$('toast');\n"
"  el.textContent=msg;\n"
"  el.className='show'+(err?' err':'');\n"
"  clearTimeout(el._t);\n"
"  el._t=setTimeout(function(){el.className='';},3500);\n"
"}\n"
"function api(method,path,body){\n"
"  return fetch(path,{method:method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined})\n"
"    .then(function(r){if(!r.ok)throw new Error(r.status);return r.json();});\n"
"}\n"
"function tab(id){\n"
"  ['status','cache','ota','interfaces'].forEach(function(t){\n"
"    $('p-'+t).classList.toggle('active',t===id);\n"
"    $('btn-'+t).classList.toggle('active',t===id);\n"
"  });\n"
"  if(id==='status')loadStatus();\n"
"  if(id==='cache')loadCache();\n"
"  if(id==='interfaces')loadIfc();\n"
"}\n"
"function fmtUp(s){\n"
"  var d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60),sec=s%60;\n"
"  return d+'d '+pad(h)+'h '+pad(m)+'m '+pad(sec)+'s';\n"
"}\n"
"function pad(n){return n<10?'0'+n:''+n;}\n"
"var _sysIp='0.0.0.0';\n"
"var _wifiData=null;\n"
"function buildNetRow(w){\n"
"  if(w&&w.state)_wifiData=w;\n"
"  var html='';\n"
"  var ethOk=_sysIp&&_sysIp!=='0.0.0.0';\n"
"  html+=row('Ethernet',ethOk?badge('Forbundet','ok')+' &nbsp;'+_sysIp:badge('Ikke tilsluttet','err'));\n"
"  if(_wifiData){\n"
"    var wst={disabled:'Deaktiveret',connecting:'Forbinder...',connected:'Forbundet',ap_mode:'AP hotspot',error:'Fejl'};\n"
"    var wcls={connected:'ok',error:'err',ap_mode:'warn'};\n"
"    var wd=_wifiData;\n"
"    html+=row('WiFi',badge(wst[wd.state]||wd.state,wcls[wd.state]||''));\n"
"    if(wd.state==='connected'&&wd.ssid)html+=row('SSID',wd.ssid);\n"
"    if(wd.state==='connected'&&wd.ip)html+=row('WiFi IP',wd.ip);\n"
"    if(wd.state==='connected'&&wd.rssi)html+=row('RSSI',wd.rssi+' dBm');\n"
"  }else{\n"
"    html+=row('WiFi','&mdash;');\n"
"  }\n"
"  $('t-net').innerHTML=html;\n"
"}\n"
"var PAR_SHORT=['N','O','E'];\n"
"function loadIfcSummary(){\n"
"  api('GET','/api/v1/interfaces').then(function(ifc){\n"
"    if(!ifc.length){$('t-ifc').innerHTML=row('','Ingen interfaces');return;}\n"
"    $('t-ifc').innerHTML=ifc.map(function(f){\n"
"      var nm=f.name?'<span style=\"color:#2563eb;font-weight:600\">'+f.name+'</span> &mdash; ':'';\n"
"      return row('Modbus'+f.id,\n"
"        nm+(f.enabled?badge('Aktiv','ok'):badge('Inaktiv','err'))+' &nbsp;'+\n"
"        f.type+' &nbsp; '+f.baudrate+'B-'+f.data_bits+(PAR_SHORT[f.parity]||'N')+f.stop_bits);\n"
"    }).join('');\n"
"  }).catch(function(){$('t-ifc').innerHTML=row('Fejl','Kunne ikke hente interfaces');});\n"
"}\n"
"function loadStatus(){\n"
"  api('GET','/api/v1/system').then(function(s){\n"
"    _sysIp=s.ip||'0.0.0.0';\n"
"    $('t-sys').innerHTML=\n"
"      row('Version','v'+s.version+' b'+(s.build||'?'))+\n"
"      row('Uptime',fmtUp(s.uptime_s))+\n"
"      row('Fri heap',Math.round(s.free_heap/1024)+' KB');\n"
"    $('hdr-info').textContent='v'+s.version+' • '+(s.ip||'?');\n"
"    buildNetRow();\n"
"  }).catch(function(){$('t-sys').innerHTML=row('Fejl','Ingen forbindelse');});\n"
"  api('GET','/api/v1/system/wifi').then(buildNetRow).catch(buildNetRow);\n"
"  loadIfcSummary();\n"
"}\n"
"var _ota=null,_poll=null;\n"
"function otaCheck(){\n"
"  $('t-ota').innerHTML=row('','Tjekker GitHub...');\n"
"  $('btn-flash').style.display='none';\n"
"  api('GET','/api/v1/system/ota/check').then(function(o){\n"
"    _ota=o;\n"
"    $('t-ota').innerHTML=\n"
"      row('Installeret',o.current_version)+\n"
"      row('Tilg&aelig;ngelig',o.firmware_available?(o.latest_version||'&mdash;'):'&mdash;')+\n"
"      row('Status',o.firmware_available?badge('Opdatering tilg&aelig;ngelig','warn'):badge('Firmware opdateret','ok'));\n"
"    if(o.firmware_available)$('btn-flash').style.display='';\n"
"  }).catch(function(){\n"
"    $('t-ota').innerHTML='<tr><td colspan=\"2\" style=\"color:#dc2626\">Kunne ikke kontakte GitHub</td></tr>';\n"
"    toast('GitHub ikke tilg&aelig;ngeligt',true);\n"
"  });\n"
"}\n"
"function otaFlash(){\n"
"  if(!_ota||!_ota.firmware_url)return;\n"
"  $('btn-flash').disabled=true;\n"
"  $('ota-prog').style.display='';\n"
"  $('ota-txt').textContent='Starter firmware-opdatering...';\n"
"  api('POST','/api/v1/system/ota/firmware',{url:_ota.firmware_url}).then(function(){\n"
"    _poll=setInterval(pollOta,1500);\n"
"  }).catch(function(){toast('OTA fejlede',true);$('btn-flash').disabled=false;});\n"
"}\n"
"var OTA_ST={idle:'Venter',checking:'Tjekker',downloading:'Downloader',flashing:'Flasher',done:'F&aelig;rdig &mdash; genstarter...',error:'Fejl'};\n"
"function pollOta(){\n"
"  api('GET','/api/v1/system/ota/status').then(function(s){\n"
"    $('ota-fill').style.width=(s.progress_pct||0)+'%';\n"
"    $('ota-txt').innerHTML=(OTA_ST[s.state]||s.state)+(s.error?' &mdash; '+s.error:'');\n"
"    if(s.state==='done'||s.state==='error'){\n"
"      clearInterval(_poll);\n"
"      if(s.state==='error'){toast('OTA fejl: '+s.error,true);$('btn-flash').disabled=false;}\n"
"    }\n"
"  }).catch(function(){});\n"
"}\n"
"var BAUDS=[1200,2400,4800,9600,19200,38400,57600,115200];\n"
"var PARITY=[['Ingen (N)','0'],['Ulige (O)','1'],['Lige (E)','2']];\n"
"function loadIfc(){\n"
"  $('ifc-list').innerHTML='<p style=\"color:#aaa;padding:12px\">Indl&aelig;ser...</p>';\n"
"  api('GET','/api/v1/interfaces').then(function(ifc){\n"
"    renderIfc(ifc);\n"
"  }).catch(function(){$('ifc-list').innerHTML='<p style=\"color:#dc2626;padding:12px\">Fejl ved indl&aelig;sning</p>';});\n"
"}\n"
"var MAX_IFACES=8;\n"
"function renderIfc(list){\n"
"  var html='';\n"
"  if(!list.length){\n"
"    html='<p style=\"color:#aaa;padding:12px\">Ingen interfaces</p>';\n"
"  }else{\n"
"    html=list.map(function(f){\n"
"      var bOpts=BAUDS.map(function(b){return '<option value=\"'+b+'\"'+(b==f.baudrate?' selected':'')+'>'+b+'</option>';}).join('');\n"
"      var pOpts=PARITY.map(function(p){return '<option value=\"'+p[1]+'\"'+(p[1]==f.parity?' selected':'')+'>'+p[0]+'</option>';}).join('');\n"
"      var isSlave=(f.mode==='slave');\n"
"      var uartLabel=(f.uart_mode==='hw'?'UART'+f.uart:'SW-UART');\n"
"      var delDis=(list.length<=1?' disabled title=\"Mindst &eacute;t interface skal forblive\"':'');\n"
"      var isRS485=(f.type==='RS485');\n"
"      var nm=f.name||('modbus'+f.id);\n"
"      return '<div class=\"ifc '+(f.enabled?'':'off')+'\" id=\"ifc'+f.id+'\">'+\n"
"        '<div class=\"ifc-hdr\">'+\n"
"        '<span class=\"ifc-name\">Modbus'+f.id+' &mdash; <em style=\"color:#2563eb;font-style:normal\">'+nm+'</em> &mdash; '+f.type+' &mdash; '+uartLabel+'</span>'+\n"
"        '<label class=\"tog\">'+\n"
"        '<input type=\"checkbox\" id=\"en'+f.id+'\" '+(f.enabled?'checked':'')+' onchange=\"toggleIfc('+f.id+')\">'+\n"
"        '<div class=\"ttrack\"></div>'+\n"
"        '<span style=\"font-size:12px;color:#666\" id=\"enlbl'+f.id+'\">'+(f.enabled?'Aktiv':'Inaktiv')+'</span>'+\n"
"        '</label></div>'+\n"
"        '<div class=\"grid\">'+\n"
"        '<label>Navn (API alias)<input type=\"text\" id=\"nm'+f.id+'\" value=\"'+nm+'\" maxlength=\"23\" placeholder=\"modbus'+f.id+'\"></label>'+\n"
"        '<label>Rolle<select id=\"mode'+f.id+'\" onchange=\"toggleMode('+f.id+')\">'+\n"
"        '<option value=\"master\"'+(isSlave?'':' selected')+'>Master</option>'+\n"
"        '<option value=\"slave\"'+(isSlave?' selected':'')+'>Slave</option>'+\n"
"        '</select></label>'+\n"
"        '<label id=\"slabel'+f.id+'\" style=\"display:'+(isSlave?'flex':'none')+'\">Slave-adr<input type=\"number\" id=\"addr'+f.id+'\" value=\"'+f.slave_addr+'\" min=\"1\" max=\"247\"></label>'+\n"
"        '<label>Type<select id=\"typ'+f.id+'\" onchange=\"toggleType('+f.id+')\">'+\n"
"        '<option value=\"RS485\"'+(isRS485?' selected':'')+'>RS485</option>'+\n"
"        '<option value=\"RS232\"'+(isRS485?'':' selected')+'>RS232</option>'+\n"
"        '</select></label>'+\n"
"        '<label>Baudrate<select id=\"baud'+f.id+'\">'+bOpts+'</select></label>'+\n"
"        '<label>Paritet<select id=\"par'+f.id+'\">'+pOpts+'</select></label>'+\n"
"        '<label>Stop bits<select id=\"stop'+f.id+'\">'+\n"
"        '<option value=\"1\"'+(f.stop_bits==1?' selected':'')+'>1</option>'+\n"
"        '<option value=\"2\"'+(f.stop_bits==2?' selected':'')+'>2</option>'+\n"
"        '</select></label>'+\n"
"        '<label>Timeout (ms)<input type=\"number\" id=\"to'+f.id+'\" value=\"'+f.timeout_ms+'\" min=\"50\" max=\"5000\" step=\"50\"></label>'+\n"
"        '<label>TX GPIO<input type=\"number\" id=\"tx'+f.id+'\" value=\"'+f.tx_pin+'\" min=\"-1\" max=\"39\"></label>'+\n"
"        '<label>RX GPIO<input type=\"number\" id=\"rx'+f.id+'\" value=\"'+f.rx_pin+'\" min=\"-1\" max=\"39\"></label>'+\n"
"        '<label id=\"delabel'+f.id+'\" style=\"display:'+(isRS485?'flex':'none')+'\">DE GPIO (RS485)<input type=\"number\" id=\"de'+f.id+'\" value=\"'+f.rts_pin+'\" min=\"-1\" max=\"39\"></label>'+\n"
"        '</div>'+\n"
"        '<div class=\"row\" style=\"justify-content:space-between\">'+\n"
"        '<button class=\"btn btn-d btn-sm\" onclick=\"deleteIfc('+f.id+')\"'+delDis+'>&minus; Slet Modbus'+f.id+'</button>'+\n"
"        '<button class=\"btn btn-p btn-sm\" onclick=\"saveIfc('+f.id+')\">Gem Modbus'+f.id+'</button>'+\n"
"        '</div></div>';\n"
"    }).join('');\n"
"  }\n"
"  var addDis=(list.length>=MAX_IFACES?' disabled title=\"Max '+MAX_IFACES+' interfaces\"':'');\n"
"  html+='<div class=\"row\" style=\"justify-content:flex-start;margin-top:6px\">'+\n"
"        '<button class=\"btn btn-p btn-sm\" onclick=\"addIfc()\"'+addDis+'>+ Tilf&oslash;j Modbus interface</button>'+\n"
"        '<span style=\"font-size:12px;color:#888;align-self:center\">&nbsp;'+list.length+' / '+MAX_IFACES+' interfaces</span>'+\n"
"        '</div>';\n"
"  $('ifc-list').innerHTML=html;\n"
"}\n"
"function toggleIfc(id){\n"
"  var on=$('en'+id).checked;\n"
"  $('ifc'+id).classList.toggle('off',!on);\n"
"  $('enlbl'+id).textContent=on?'Aktiv':'Inaktiv';\n"
"}\n"
"function toggleMode(id){\n"
"  var isSlave=($('mode'+id).value==='slave');\n"
"  $('slabel'+id).style.display=isSlave?'flex':'none';\n"
"}\n"
"function toggleType(id){\n"
"  var isRS485=($('typ'+id).value==='RS485');\n"
"  $('delabel'+id).style.display=isRS485?'flex':'none';\n"
"}\n"
"function saveIfc(id){\n"
"  var body={\n"
"    name:($('nm'+id).value||'').trim(),\n"
"    mode:$('mode'+id).value,\n"
"    slave_addr:parseInt($('addr'+id).value)||1,\n"
"    type:$('typ'+id).value,\n"
"    baudrate:parseInt($('baud'+id).value),\n"
"    parity:parseInt($('par'+id).value),\n"
"    stop_bits:parseInt($('stop'+id).value),\n"
"    timeout_ms:parseInt($('to'+id).value),\n"
"    tx_pin:parseInt($('tx'+id).value),\n"
"    rx_pin:parseInt($('rx'+id).value),\n"
"    rts_pin:parseInt($('de'+id).value),\n"
"    enabled:$('en'+id).checked\n"
"  };\n"
"  api('PUT','/api/v1/interfaces/'+id,body).then(function(){\n"
"    toast('Modbus'+id+' gemt &mdash; reboot for at aktivere');\n"
"    loadIfc();\n"
"  }).catch(function(){toast('Fejl ved gem Modbus'+id,true);});\n"
"}\n"
"function addIfc(){\n"
"  api('POST','/api/v1/interfaces',{}).then(function(f){\n"
"    toast('Modbus'+f.id+' oprettet &mdash; konfigurer GPIO via CLI, reboot');\n"
"    loadIfc();\n"
"  }).catch(function(){toast('Fejl ved oprettelse',true);});\n"
"}\n"
"function deleteIfc(id){\n"
"  if(!confirm('Slet Modbus'+id+'?'))return;\n"
"  fetch('/api/v1/interfaces/'+id,{method:'DELETE'}).then(function(r){\n"
"    if(!r.ok)throw new Error(r.status);\n"
"    toast('Modbus'+id+' slettet &mdash; reboot for at aktivere');\n"
"    loadIfc();\n"
"  }).catch(function(){toast('Fejl ved sletning Modbus'+id,true);});\n"
"}\n"
"function doReboot(){\n"
"  if(!confirm('Genstart gateway?'))return;\n"
"  api('POST','/api/v1/system/reboot').then(function(){toast('Genstarter...');}).catch(function(){});\n"
"}\n"
"function loadCache(){\n"
"  api('GET','/api/v1/cache/stats').then(function(s){\n"
"    $('cache-en').checked=s.enabled;\n"
"    $('cache-ttl').value=s.ttl_ms;\n"
"    $('t-cache-stats').innerHTML=\n"
"      row('Status',          s.enabled?badge('Aktiv','ok'):badge('Deaktiveret','err'))+\n"
"      row('TTL',              s.ttl_ms==0?'0 ms (aldrig udløb)':s.ttl_ms+' ms')+\n"
"      row('Entries',          s.entries_used+' / '+s.max_entries+'  ('+s.utilization_pct.toFixed(1)+'%)')+\n"
"      row('Hits',             s.hits)+\n"
"      row('Misses',           s.misses)+\n"
"      row('Hit rate',         s.hit_rate_pct.toFixed(1)+'%')+\n"
"      row('Errors',           s.errors)+\n"
"      row('Evictions',        s.evictions)+\n"
"      row('Total requests',   s.total_requests)+\n"
"      row('Bg-refreshes',     s.refresh_done+' OK / '+s.refresh_failed+' fejl');\n"
"  }).catch(function(){$('t-cache-stats').innerHTML=row('Fejl','Ingen forbindelse');});\n"
"  api('GET','/api/v1/cache/history').then(renderHistory).catch(function(){});\n"
"  api('GET','/api/v1/cache/entries').then(function(ents){\n"
"    if(!ents.length){$('cache-table').innerHTML='<p style=\"color:#aaa;padding:12px\">Ingen entries</p>';return;}\n"
"    var h='<table class=\"info\" style=\"font-size:12px\"><thead><tr style=\"background:#f3f4f6;font-weight:600\">'+\n"
"      '<td>iface</td><td>slave</td><td>FC</td><td>addr</td><td>value</td><td>status</td><td>hits</td><td>age (ms)</td></tr></thead><tbody>';\n"
"    h+=ents.map(function(e){\n"
"      var st=e.status==='valid'?badge('valid','ok'):(e.status==='error'?badge('error','err'):badge(e.status,''));\n"
"      return '<tr><td>'+e.iface+'</td><td>'+e.slave+'</td><td>'+e.fc+'</td><td>'+e.addr+'</td><td>'+e.value+'</td><td>'+st+'</td><td>'+e.hits+'</td><td>'+e.age_ms+'</td></tr>';\n"
"    }).join('');\n"
"    h+='</tbody></table>';\n"
"    $('cache-table').innerHTML=h;\n"
"  }).catch(function(){$('cache-table').innerHTML='<p style=\"color:#dc2626;padding:12px\">Fejl ved indl&aelig;sning</p>';});\n"
"}\n"
"function renderHistory(samples){\n"
"  var svg=$('svg-hist');\n"
"  if(!samples||samples.length<2){svg.innerHTML='<text x=\"300\" y=\"90\" text-anchor=\"middle\" fill=\"#aaa\" font-size=\"12\">Indsamler data... (mindst 2 samples kr&aelig;ves)</text>';return;}\n"
"  // Samples er nyeste først — vend om for kronologisk visning\n"
"  var s=samples.slice().reverse();\n"
"  var dt=[];\n"
"  for(var i=1;i<s.length;i++){\n"
"    var dms=Math.max(s[i].t-s[i-1].t,1);\n"
"    var dh=s[i].hits-s[i-1].hits;\n"
"    var dm=s[i].miss-s[i-1].miss;\n"
"    var dr=s[i].rfr-s[i-1].rfr;\n"
"    var dtot=dh+dm;\n"
"    dt.push({\n"
"      hit_rate:dtot>0?(100*dh/dtot):0,\n"
"      req_per_s:dtot*1000/dms,\n"
"      rfr_per_s:dr*1000/dms,\n"
"      t:s[i].t\n"
"    });\n"
"  }\n"
"  if(!dt.length){svg.innerHTML='';return;}\n"
"  var W=600,H=180,pad=24;\n"
"  var maxReq=Math.max.apply(null,dt.map(function(d){return Math.max(d.req_per_s,d.rfr_per_s)}));\n"
"  if(maxReq<1)maxReq=1;\n"
"  var x=function(i){return pad+(W-2*pad)*i/(dt.length-1||1);};\n"
"  var yHit=function(v){return H-pad-(H-2*pad)*v/100;};\n"
"  var yReq=function(v){return H-pad-(H-2*pad)*v/maxReq;};\n"
"  // Gitter\n"
"  var grid='';\n"
"  for(var gi=0;gi<=4;gi++){\n"
"    var gy=pad+(H-2*pad)*gi/4;\n"
"    grid+='<line x1=\"'+pad+'\" y1=\"'+gy+'\" x2=\"'+(W-pad)+'\" y2=\"'+gy+'\" stroke=\"#e5e7eb\" stroke-width=\"1\"/>';\n"
"  }\n"
"  // Tre polylines\n"
"  var pHit=dt.map(function(d,i){return x(i)+','+yHit(d.hit_rate);}).join(' ');\n"
"  var pReq=dt.map(function(d,i){return x(i)+','+yReq(d.req_per_s);}).join(' ');\n"
"  var pRfr=dt.map(function(d,i){return x(i)+','+yReq(d.rfr_per_s);}).join(' ');\n"
"  // Akse-labels\n"
"  var lbl='<text x=\"'+(pad-2)+'\" y=\"'+pad+'\" text-anchor=\"end\" font-size=\"10\" fill=\"#666\">100%</text>'+\n"
"          '<text x=\"'+(pad-2)+'\" y=\"'+(H-pad+4)+'\" text-anchor=\"end\" font-size=\"10\" fill=\"#666\">0%</text>'+\n"
"          '<text x=\"'+(W-pad+2)+'\" y=\"'+pad+'\" font-size=\"10\" fill=\"#666\">'+maxReq.toFixed(1)+'/s</text>'+\n"
"          '<text x=\"'+(W-pad+2)+'\" y=\"'+(H-pad+4)+'\" font-size=\"10\" fill=\"#666\">0/s</text>';\n"
"  svg.innerHTML=grid+\n"
"    '<polyline fill=\"none\" stroke=\"#2563eb\" stroke-width=\"2\" points=\"'+pHit+'\"/>'+\n"
"    '<polyline fill=\"none\" stroke=\"#dc2626\" stroke-width=\"2\" points=\"'+pReq+'\"/>'+\n"
"    '<polyline fill=\"none\" stroke=\"#16a34a\" stroke-width=\"2\" points=\"'+pRfr+'\"/>'+\n"
"    lbl;\n"
"  var last=dt[dt.length-1];\n"
"  var sumReq=dt.reduce(function(a,d){return a+d.req_per_s;},0)/dt.length;\n"
"  $('t-hist-summary').innerHTML=\n"
"    row('Senest m&aring;lt hit rate',last.hit_rate.toFixed(1)+'%')+\n"
"    row('Senest m&aring;lt requests/s',last.req_per_s.toFixed(2))+\n"
"    row('Senest m&aring;lt refresh/s',last.rfr_per_s.toFixed(2))+\n"
"    row('Gennemsnit requests/s',sumReq.toFixed(2))+\n"
"    row('Tidsvindue',Math.round((dt[dt.length-1].t-dt[0].t)/1000)+' s ('+dt.length+' samples)');\n"
"}\n"
"function saveCacheCfg(){\n"
"  api('PUT','/api/v1/cache/config',{enabled:$('cache-en').checked,ttl_ms:parseInt($('cache-ttl').value)||0,refresh_enabled:$('cache-rfr').checked}).then(function(){\n"
"    toast('Cache-konfiguration gemt');loadCache();\n"
"  }).catch(function(){toast('Fejl ved gem',true);});\n"
"}\n"
"function clearCache(){\n"
"  if(!confirm('T\\u00f8m hele cachen?'))return;\n"
"  fetch('/api/v1/cache/clear',{method:'POST'}).then(function(r){if(!r.ok)throw 0;toast('Cache t\\u00f8mt');loadCache();}).catch(function(){toast('Fejl',true);});\n"
"}\n"
"function resetCacheStats(){\n"
"  fetch('/api/v1/cache/reset-stats',{method:'POST'}).then(function(r){if(!r.ok)throw 0;toast('Stats nulstillet');loadCache();}).catch(function(){toast('Fejl',true);});\n"
"}\n"
"loadStatus();\n"
"</script>\n"
"</body>\n"
"</html>\n"
;

static esp_err_t get_mgmt_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
    httpd_resp_send(req, mgmt_html, sizeof(mgmt_html) - 1);
    return ESP_OK;
}

const httpd_uri_t route_get_mgmt = {
    .uri     = "/mgmt",
    .method  = HTTP_GET,
    .handler = get_mgmt_handler,
};
